document:
  type: Linee guida
  name: Regole Tecniche per la firma tramite SPID
  short_name: Ll.gg. Firma SPID
  author: walter-arrighetti
  contributors:
    - Stefano Arbia
    - Walter Arrighetti
    - Michele D'Amico
    - Antonio Florio
    - Stefano Ianniello
    - Andrea Spallacci
  description: |
    Linee Guida contenenti Regole Tecniche circa la sottoscrizione elettronica di documenti tramite SPID ex art. 20 del CAD
  tags:
    - SPID
    - eIDAS
    - sottoscrizione
    - firma elettronica
    - sigillo elettronico qualificato
    - QSeal
  origin: https://github.com/test-lg/llgg01_SPID_firma
