document:
  name: Linee Guida sottoscrizione ex art.20 CAD
  description: |
    Linee Guida contenenti Regole Tecniche circa la sottoscrizione elettronica di documenti tramite SPID ex art. 20 del CAD
  tags:
    - "SPID"
